---

#- name: Create virtual network for acm (will be use the same network)
#  azure_rm_virtualnetwork:
#    resource_group: "{{ azure_resource_group }}"
#    name: "{{ azure_vnet_name }}"
#    address_prefixes: "{{ azure_vnet_acm_cidr }}"

- name: Add subnet for control-plane for acm
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: control-plane-acm
    address_prefix: "{{ azure_subnet_acm_controlplane }}"
    virtual_network: "{{ azure_vnet_name }}"

- name: Add subnet for compute for acm
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: compute-acm
    address_prefix: "{{ azure_subnet_acm_compute }}"
    virtual_network: "{{ azure_vnet_name }}"

- name: Add subnet for bastion
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: bastion-acm
    address_prefix: "{{ azure_subnet_acm_bastion }}"
    virtual_network: "{{ azure_vnet_name }}"

- name: Update the route subnet for control-plane
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: control-plane-acm
    address_prefix: "{{ azure_subnet_acm_controlplane }}"
    virtual_network: "{{ azure_vnet_name }}"
    route_table: "{{ azure_fw_rt }}"

- name: Add subnet for compute
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: compute-acm
    address_prefix: "{{ azure_subnet_acm_compute }}"
    virtual_network: "{{ azure_vnet_name }}"
    route_table: "{{ azure_fw_rt }}"

